name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-compiler:
          - 4.08.1
          - 4.14.2
          - 5.3.0
        exclude:
          - os: macos-latest
            ocaml-compiler: 4.08.1

    env:
      OPAMYES: "true"

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup OCaml ${{ matrix.ocaml-compiler }}
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}
        dune-cache: true

    - name: Update repository
      run: opam update
    - name: Install dependencies
      run: opam install . --deps-only --with-test
    - name: Build the package
      run: opam exec -- make
    - name: Run tests
      run: opam exec -- make test
